- name: include variables
  include_vars: "{{ playbook_dir }}/config.yml"

- name: "Force shutdown !!!!!!!!!!"
  uri:
    url: http://apiv2/v2/iaas/virtual-machines/{{ vm_id }}/shutdown
    method: PUT
    headers:
      Authorization: "Bearer {{ user_token }}"
    body: "force=1"
    return_content: yes
    status_code: 204

- name: wait for config apply
  wait_for:
    timeout: 10
  
- name: "Delete halted VM !!!!!!!!!!"
  uri:
    url: http://apiv2/v2/iaas/virtual-machines/{{ vm_id }}
    method: DELETE
    headers:
      Authorization: "Bearer {{ user_token }}"
    body: "force=1" 
    return_content: yes
    status_code: 204
  ignore_errors: True

- meta: end_play