---
- name: drop proxy conf
  hosts: netgateway
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.netgateway.proxy.configure
  vars: 
    - domain_name: deneme123.com
    - ip_address: 10.100.0.23
    - port: 99