- name: Discover Netgateway Server
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.check.metadata
    -  role: plusclouds.environment.information
  vars:
    - netgateway: "yDQLBJjLwm"
    - user_token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjFhNWNmZDM2OTg0ZjFiODg1ZmQ2YzA2N2FkZjg3MDc0MGY1YTBkYTI2NDgyZmZkMjQxMjNkNjNjOGZjNDY3MjJiMmI0YjM4MjkwODFiM2YxIn0.eyJhdWQiOiIzOSIsImp0aSI6IjFhNWNmZDM2OTg0ZjFiODg1ZmQ2YzA2N2FkZjg3MDc0MGY1YTBkYTI2NDgyZmZkMjQxMjNkNjNjOGZjNDY3MjJiMmI0YjM4MjkwODFiM2YxIiwiaWF0IjoxNjU4OTk5NTg5LCJuYmYiOjE2NTg5OTk1ODksImV4cCI6MTY5MDUzNTU4OSwic3ViIjoiMTY3MDMiLCJzY29wZXMiOltdfQ.RI5jkiXtQw7WcFiV8sbvxutn4VU3VIQ1_tnIbgrBJgE8oLoGD1FXxce_fwkdAsttwWFhHFJlVKNrh8V37tqqcW9nXUIrQdilIJ0NYePfoV_rUKSLRguhywBnu288PkIFmNy4qSaB81BRUj8m1M-NXm6aTLscE8G-BcfDC96anbKR_rItx6U5wYh6U3DL-OmYxODSnfg0uz55EPvbEPddWg8YI8PB6LtFMQk-3FouE6qbfV4bcNiO4Iv9IscCuYZz0ZPlUzvKdbw_vgrVZfw_fSF9fJeZjWKTJomxFDe7YWbURpA8AU-wqFi8kSGf9OJ0W2gYdmn2ZFzdIDXnqIoTCVsWuQg3bnq5WBcA619oCqGKlfdvQx85qWJJ4F3nFkNsCXBG2QwTDHA2xISDbVw-V9qFyk_Vy3KkN5aWpTg46oYrInJLL4rJfzu2EHC71UlqGJcoKHg7Y95mqN-K_AHP1pykLx-gCsuC-BSOAmWori2FLqD7m3jm7JfTz7t_iFhMBhHAMMLsfOyNEKUXElj4xz7VNDLd1BKUbXPG0jGyrXpg5qpSnQ7atCEsf4zwHvja3t0D_owDbBMCgY1kftlBKJBbFVhM7K7wnypoZSUFvW-CzIfs4zyeOfK_hp0igZSUjK-WEKKelAOzE_mVMK95gzAvIADITOLegJaVsu7x3Iw"
    - leo_url: http://10.100.0.25
- name: Add client
  hosts: netgateway
  gather_facts: true
  roles:
    -  role: plusclouds.packetbender.openvpn/plusclouds.packetbender.openvpn.add.client
  vars:
    - client: user2
    - netgateway: "yDQLBJjLwm"
    - user_token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjFhNWNmZDM2OTg0ZjFiODg1ZmQ2YzA2N2FkZjg3MDc0MGY1YTBkYTI2NDgyZmZkMjQxMjNkNjNjOGZjNDY3MjJiMmI0YjM4MjkwODFiM2YxIn0.eyJhdWQiOiIzOSIsImp0aSI6IjFhNWNmZDM2OTg0ZjFiODg1ZmQ2YzA2N2FkZjg3MDc0MGY1YTBkYTI2NDgyZmZkMjQxMjNkNjNjOGZjNDY3MjJiMmI0YjM4MjkwODFiM2YxIiwiaWF0IjoxNjU4OTk5NTg5LCJuYmYiOjE2NTg5OTk1ODksImV4cCI6MTY5MDUzNTU4OSwic3ViIjoiMTY3MDMiLCJzY29wZXMiOltdfQ.RI5jkiXtQw7WcFiV8sbvxutn4VU3VIQ1_tnIbgrBJgE8oLoGD1FXxce_fwkdAsttwWFhHFJlVKNrh8V37tqqcW9nXUIrQdilIJ0NYePfoV_rUKSLRguhywBnu288PkIFmNy4qSaB81BRUj8m1M-NXm6aTLscE8G-BcfDC96anbKR_rItx6U5wYh6U3DL-OmYxODSnfg0uz55EPvbEPddWg8YI8PB6LtFMQk-3FouE6qbfV4bcNiO4Iv9IscCuYZz0ZPlUzvKdbw_vgrVZfw_fSF9fJeZjWKTJomxFDe7YWbURpA8AU-wqFi8kSGf9OJ0W2gYdmn2ZFzdIDXnqIoTCVsWuQg3bnq5WBcA619oCqGKlfdvQx85qWJJ4F3nFkNsCXBG2QwTDHA2xISDbVw-V9qFyk_Vy3KkN5aWpTg46oYrInJLL4rJfzu2EHC71UlqGJcoKHg7Y95mqN-K_AHP1pykLx-gCsuC-BSOAmWori2FLqD7m3jm7JfTz7t_iFhMBhHAMMLsfOyNEKUXElj4xz7VNDLd1BKUbXPG0jGyrXpg5qpSnQ7atCEsf4zwHvja3t0D_owDbBMCgY1kftlBKJBbFVhM7K7wnypoZSUFvW-CzIfs4zyeOfK_hp0igZSUjK-WEKKelAOzE_mVMK95gzAvIADITOLegJaVsu7x3Iw"
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
