- name: Discover Netgateway Server
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.netgateway.configs.get
    -  role: plusclouds.environment.information
  vars:
    datacenter_node: yVMNlGrzlo

- name: Add loadbalancer
  hosts: netgateway
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.environment.information
    -  role: plusclouds.netgateway.configs.get
    -  role: plusclouds.netgateway.loadbalancer.add
  vars: 
    - domain_name: "demo.com" 
    - nodes: "10.100.0.100:81,10.100.0.88:82,10.100.0.93:20,10.100.0.93:21,10.100.0.93:22" 
    - balancing_method: "least_conn" #default round robin empty, least_conn, ip-hash
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
