- name: Discover Netgateway Server
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.check.metadata
    -  role: plusclouds.environment.information
  vars:
    - netgateway: "jGMNKKzNbK"
    - user_token: ""
    - leo_url: http://10.100.0.25
- name: Add client
  hosts: netgateway
  gather_facts: true
  roles:
    -  role: plusclouds.packetbender.openvpn/plusclouds.packetbender.openvpn.add.client
  vars:
    - client: user2
    - netgateway: "jGMNKKzNbK"
    - user_token: ""
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
