---
- name: Add NAT Rule
  hosts: netgateway
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.netgateway.iptables.add.rule
  vars: 
    - nat_port: 10000
    - destination_ip: 8.8.4.4
    - destination_port: 80