---
- name: Discover Netgateway Server
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.netgateway.configs.get
    -  role: plusclouds.environment.information
  vars:
    - netgateway: "jGMNKqvLbK"
    - user_token: ""
    - leo_url: http://10.100.0.114

- name: Add Proxy Rule
  hosts: netgateway
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.environment.information
    -  role: plusclouds.netgateway.configs.get
    -  role: plusclouds.netgateway.proxy.configure
  vars: 
    - netgateway: "jGMNKqvLbK"
    - user_token: ""
    - leo_url: http://10.100.0.114
    - domain_name: demo.com
    - ip_address: 8.8.4.4
    - port: 105
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
