---
- name: Add Proxy Rule
  hosts: netgateway
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.netgateway.proxy.configure
  vars: 
    - domain_name: myproxy.com
    - ip_address: 8.8.4.4
    - port: 80