- name: Discover Netgateway Server
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.netgateway.configs.get
    -  role: plusclouds.environment.information
  vars:
    - netgateway: "jGMNKqvLbK"
    - user_token: ""
    - leo_url: http://10.100.0.114

- name: Add loadbalancer node
  hosts: netgateway
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.environment.information
    -  role: plusclouds.netgateway.configs.get
    -  role: plusclouds.netgateway.loadbalancer.node.add
  vars: 
    - domain_name: "demo.com"
    - new_node: "10.128.30.75:999"
    - user_token: ""
    - leo_url: http://10.100.0.114
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
