- name: Discover Netgateway Server
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.environment.information
  vars:
    datacenter_node: yVMNlGrzlo

- name: Add loadbalancer node
  hosts: netgateway
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.netgateway.loadbalancer.node.add
  vars: 
    - domain_name: "demo"
    - new_node: "10.100.0.999:999"
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
