---
application: "demo"
user_token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjJhY2M4ODRhNmM2ODM4NzBjNTNhZDI3ZmJlMjMxNjM2ZGNhYzJlN2FiMWI3NWEwNzRlODU0YjI0M2YxN2FiOTdmMjExZWRhZDEzMzIxNzljIn0.eyJhdWQiOiIyIiwianRpIjoiMmFjYzg4NGE2YzY4Mzg3MGM1M2FkMjdmYmUyMzE2MzZkY2FjMmU3YWIxYjc1YTA3NGU4NTRiMjQzZjE3YWI5N2YyMTFlZGFkMTMzMjE3OWMiLCJpYXQiOjE1NjQzOTA1NDAsIm5iZiI6MTU2NDM5MDU0MCwiZXhwIjoxNTk2MDEyOTQwLCJzdWIiOiIyMTI3Iiwic2NvcGVzIjpbXX0.EiGs5hYyQ0G93-p-tRM1uhzhO3k0983nI2HT2z0puUYpvDZrKYuXV0ZER7Vz3i_VtrwtkBKN-KyT7RD_9uVPeLSdGvwJkp8jG1I1Pj9vjC_bVDzr5HS6cIqDpVqpbe0MxOBpR0_k6WrbSQ_n2bjEt1pf0kvxt4UBTfHHn6In3PuGdQ_mTX5yGkZnBbPJW0iDHJjXuVIylLAg7OzicBPALnlt8HfWJ45WD-t8CxuyhpKRjdRtppRhYkgILzqojxz1CLCXbgeY3x2fpTzgS84klvxDRZdcU0YUlqJdCNwOudao_XUBkokOHQPo1FFU2M1ltNUQBxjN0Dg94vpoqcPCHlUgEGaXiWoQclvjHNLIXIYSXihAaHdS19vRxrq1Zk8byHYlMXj1QLT-NSkihtiUjuwqzmUkNHiI-gKZHbOQSOr_oRki2JJKbzeai8U3ORFVowM3nBip9iecGRS2cuTSQ89qeBr9wTLN8XESu4ms-ci7OMk4jW83EeMbUW8EeAFBeFczvVnJ4nmmfAkM-NC-YuDihEVTQFOW_-vqLpg8EUz_GMzXGZbiOG_gPeQrTYE24xl1cE-WTvGY2M4Ay5dkZFWVONfNzxb9LyO7nHUUPAjB8Bvrwq39DD_CxcimmCvKFBFoZdHNpufcCJbV859z_8I73FfTH3j2SpziKzumye4"

gitlab_token: "ztehjcYFgjiVxchWayzt"
gitlab_project_id: 52

gitlab_title: "test title"
gitlab_description: "test description"
gitlab_assignee_id: "2"

#preferred_template_distribution: "centos"
#preferred_template_version: "7"
#preferred_template_tag: "template v1.1"
#
#preferred_node_slug: "mednautilus-cell5"
preferred_node: "XzBYDyLvgq"

preferred_template_distribution: "debian"
preferred_template_version: "9.9"
preferred_template_tag: "template v1.1"

preferred_node_slug: "plusclouds-management-pool-2"

preferred_database_ram: 16384
preferred_panel_ram: 2048
preferred_api_ram: 4096

netgateway_cpu: 2
netgateway_disk: 12000
netgateway_ram: 512
default_username: leo
default_password: fO0OeDwoW)bIrZuAs|aU

vlan_network_card_ref: VGxLmgzNpe
public_network_card_ref: VGxLmgzNpe
dhcp_bind: eth0
#default_username: root
#default_password: template1


# temporary variables
#ansible_ssh_user: "root"
#ansible_ssh_pass: "template1"
vlan_ip_addr: "10.100.0.1"
vlan_netmask: "255.255.0.0"
vlan_subnet: "/16"
vlan_broadcast: "10.100.255.255"
vlan_gateway: "10.100.0.1"
vlan_start_ip_range: "10.100.0.10"
vlan_end_ip_range: "10.100.255.254"
vlan_network: "10.100.0.0"
node_name: "netgateway-leo"
public_ip_addr: "10.100.0.100"
public_netmask: "255.255.0.0"
public_gateway: "10.100.0.1"