---
- name: Deploy Netgateway Server
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.netgateway.configs.get
    -  role: plusclouds.netgateway.deploy
    -  role: plusclouds.netgateway.set
  #  -  role: plusclouds.environment.information
  vars:
    - wan: "VxMNyjXYkv"
    - network: "bDqYxDnYGo"
    - datacenter_node: "yDQLBvLwmR"
    - netgateway: "bGyYjWRLEx"
    - type: "medium"
    - user_token: ""
    - leo_url: http://10.100.0.114