---
- name: Discover Netgateway Server
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.netgateway.configs.get
    -  role: plusclouds.environment.information

- name: Drop NAT Configuration
  hosts: netgateway
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.netgateway.iptables.drop.rule
  vars: 
    - source_port: 12000
    - destination_ip: 10.128.199.13
    - destination_port: 82
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
