---
- name: Deploy Netgateway Server
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.environment.information

- name: drop proxy conf
  hosts: netgateway
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.netgateway.iptables.drop.rule
  vars: 
    - nat_port: 9999
    - destination_ip: 10.100.0.2
    - destination_port: 9912