---
- name: Install netgateway services to server
  hosts: localhost
  become: false
  gather_facts: true
  roles:
   -  role: plusclouds.check.metadata
   -  role: plusclouds.netgateway.set.ipaddr
      when: not is_ipconfig_installed | bool
   -  role: plusclouds.netgateway.iptables.setup
      when: not is_iptables_installed | bool
   -  role: plusclouds.netgateway.dhcp.setup
      when: not is_dhcp_installed | bool
   -  role: plusclouds.netgateway.dhcp.add.subnet
      when: not is_dhcp_installed | bool
   -  role: plusclouds.packetbender.openvpn/plusclouds.packetbender.openvpn.setup
      when: not is_vpn_installed | bool
   -  role: plusclouds.netgateway.loadbalancer.add
      when: not is_proxy_installed | bool
   -  role: plusclouds.netgateway.iptables.setup
      when: iptables_hash != iptables_hash_meta
   -  role: plusclouds.netgateway.loadbalancer.add
      when: loadbalancer_hash != loadbalancer_hash_meta
   -  role: plusclouds.packetbender.openvpn/plusclouds.packetbender.openvpn.setup
      when: ovpnsrv_hash != ovpnsrv_hash_meta
   -  role: plusclouds.netgateway.rsyslog.install
      when: rsyslog_hash != rsyslog_hash_meta
   -  role: plusclouds.netgateway.ntp.install
      when: ntp_hash != ntp_hash_meta

  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
  vars:
    - leo_url: "http://10.100.0.25"

# set ip addresess
# install iptables
# install openvpn
# install proxy&loadbalancer
# install ntp
# install rsyslog
# install dhcp
# add subnets
