---
- name: Deploy Netgateway Server
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.netgateway.configs.get
    -  role: plusclouds.netgateway.deploy
    -  role: plusclouds.netgateway.set
    -  role: plusclouds.environment.information
  vars:
    - wan: "VxMNyjXYkv"
    - network: "yDQNBqGrwm"
    - datacenter_node: "yDQLBvLwmR"
    - netgateway: "plGYwovYwQ"
    - type: "medium"
    - user_token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjNjNzNjNmJhMGJjOTY3OGRlNTYxZDRiNzBmZmZhMzk5ZDhhMTMzNDljNmVjNzMxNDBkYjVlYjg1M2QyMDA1Y2Q1NGRkZDlhODMwYjM5ZWUwIn0.eyJhdWQiOiIyNCIsImp0aSI6IjNjNzNjNmJhMGJjOTY3OGRlNTYxZDRiNzBmZmZhMzk5ZDhhMTMzNDljNmVjNzMxNDBkYjVlYjg1M2QyMDA1Y2Q1NGRkZDlhODMwYjM5ZWUwIiwiaWF0IjoxNjQyMDY0NDA1LCJuYmYiOjE2NDIwNjQ0MDUsImV4cCI6MTY3MzYwMDQwNSwic3ViIjoiMTI5NTgiLCJzY29wZXMiOltdfQ.qHzTsLOTGqCMWVSkfZCwR1Y0_i27foVAsPFqQhaLh1qSYsABloIsucvMAgJXMYzRJU0y63KdbdQS9vf7F3NMfozZgR5FL3W37fGSLvU4D2zyV_SxsBEoGRPn8sTig-e54LfeMt_CbCK5p-dsNh4X2zSKSf8WsHTGJNV09LzWCjdcW00tVYKZPxXD45IYTQ_LDO4VOFfbjGsRHiM8TXpXwCh_aTzA73sgVFJhJgD7D0adwMovxqcWEeDtzTbk4NTwqp5YGB1zcEBZ9HkmBzIqRE1kc4vZFTjKf7C4k0sCXYJ8TIlAjbtoqLk9JdbEENE_vtJDWheW8pGxdi0-R9XRHjvxKUrZ5nltZJVG94dBbbdMX6RYrVVAQa74LwnukH6AakFYl-4UQ0IziAFe-LPiYM_gguEcdlsGLaxKetp8znaF40YocnsNkPBQhgaP052UCFyz4SmOwk_fotziKllXipH65h7NAf_sFiFmORL6ynJ1uAZyY14g6q7SriMUjS8AnzIJt8W4uAf5ZzaQmegA8ZgwYt0zlrrp53fEjDOgNIg6etBqWZnkY9ACSSXxajGENrM05gAQ-9FGuw12lg3E5DXFv825DNAvi3ucLO_OYzbePA_8z0w1y_xThrHBxWzPqvhHHi9i9xgQXT64IugRBlxBY_YTAed76vqpGUfPYGc"
    - leo_url: http://10.100.0.25

