---
- name: Deploy Netgateway Server
  hosts: localhost
  become: false
  gather_facts: false
  roles: 
    -  role: plusclouds.netgateway.configs.get
    -  role: plusclouds.netgateway.deploy
    -  role: plusclouds.netgateway.set
    -  role: plusclouds.environment.information
  vars:
    - wan: ""
    - network: ""
    - datacenter_node: ""
    - netgateway: ""
    - type: "small"

- name: Install netgateway services to server
  hosts: netgateway
  become: false
  gather_facts: true
  roles:
   -  role: plusclouds.environment.information
   -  role: plusclouds.netgateway.set.ipaddr
   -  role: plusclouds.random.password.change
   -  role: plusclouds.vm.set.password
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
