- name: Discover Netgateway Server
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.netgateway.configs.get
    -  role: plusclouds.environment.information
  vars:
    - netgateway: "ZaRNeZAYlv"
    - user_token: ""
    - leo_url: http://10.100.0.114

- name: Install strongswan to Netgateway
  hosts: netgateway
  become: false
  gather_facts: true
  roles:
    -  role: plusclouds.netgateway.strongswan.install
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
