---
- name: Deploy Netgateway Server
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.netgateway.deploy
    -  role: plusclouds.environment.information
    -  role: plusclouds.netgateway.set
  vars:
    - template: "wpOYoOyYzq"
    - domain_name: "plusclouds.com"
    - server_name: "NetGateway"
    - datacenter_node: "yVMNlGrzlo"
    - network: "mkgNWxxYxp"
    - cpu: "8"
    - disk_size: "10200"
    - ram_size: "1024"

- name: Install netgateway services to server
  hosts: netgateway
  become: false
  gather_facts: true
  roles:
   -  role: plusclouds.environment.information
   -  role: plusclouds.netgateway.set.ipaddr
   -  role: plusclouds.netgateway.proxy.setup
   -  role: plusclouds.netgateway.iptables.setup
   -  role: plusclouds.netgateway.dhcp.setup
   -  role: plusclouds.netgateway.dhcp.add.subnet
  vars: 
   - server_name: "NetGateway"
   - datacenter_node: "yVMNlGrzlo"