- name: Discover Netgateway Server
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.netgateway.configs.get
    -  role: plusclouds.environment.information
  vars:
    - netgateway: "RZMLnbqLGj"
    - user_token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImE5NTk2NTVlZjg2ZWUyMGRiMmM0NDdlMzY3OTMyNDZjYmVhN2Y1ODc2NjRlNGEyYjQwOTdlOTJiNTcyODJkMzZlNjRiNWI4YmFiOTg2MzE3In0.eyJhdWQiOiIyIiwianRpIjoiYTk1OTY1NWVmODZlZTIwZGIyYzQ0N2UzNjc5MzI0NmNiZWE3ZjU4NzY2NGU0YTJiNDA5N2U5MmI1NzI4MmQzNmU2NGI1YjhiYWI5ODYzMTciLCJpYXQiOjE1ODUyMjc3MDEsIm5iZiI6MTU4NTIyNzcwMSwiZXhwIjoxNjE2NzYzNzAxLCJzdWIiOiIyMTI3Iiwic2NvcGVzIjpbXX0.of9f2LtFBjsHK8fx1j9tj2OEvdFESrEiJBYO4ttcV24T9B4t0eoNFf9WIGuvJmKTbuasoJB1m0ELKw6CpW9dby1wlj44OIXfTdf1rgCFXKyX4G453w1pAZUsHPm-QZdSpftDEek37OCb7JeOzH8AKl1vxqw1-QZBkm22IITmwBVcgOOClpx9_GoTu34ECw_xg7SAPALvnydagn52OMoRP-PZGKu86M9k2ghEjiydhZsBob8HTr2dDoyvMp1g2OzjNW2QLHUc0S4hfZ051UkBkg8eX376De90wIcP1ZNrcGotHarXdZ6af0dR8ma4t1r00EDLxrBuTZdvXQH--MmuAAN5Kel1GBj1YcVyQuBR75Vqs1Q1NY6UjEnPTCvK_dbzFHvfqK_-7e-oR6LU8uNpxEjL29kMp9umV4UuPyc0Acdq-3net_hy2AhC_4-qFdW3bUMqomoJY1S7CeRVPFuq0HxF4NWgGVQiRMPDa1Tw_S2v6IEye9OSG1wlhENhiaImW413PUAM6cG9rHHFLHIj1oduNKVtmUDB6_M9FXYskkMbMiojP_8MzbtHDDMouDu0m0xhjoiv2z-9Zy1h11sCueM0telrn2b5dlXczM8Mycj6OneHXuzQvDcGfzJ7bwygl_76h1D4nmmcXLoex0HKVqx52iQ3NqMDgx3DyTwZeZw"

- name: Install proxy to Netgateway
  hosts: netgateway
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.database.mysql.install
    -  role: plusclouds.netgateway.pdns.install
  vars:
    - user_token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImE5NTk2NTVlZjg2ZWUyMGRiMmM0NDdlMzY3OTMyNDZjYmVhN2Y1ODc2NjRlNGEyYjQwOTdlOTJiNTcyODJkMzZlNjRiNWI4YmFiOTg2MzE3In0.eyJhdWQiOiIyIiwianRpIjoiYTk1OTY1NWVmODZlZTIwZGIyYzQ0N2UzNjc5MzI0NmNiZWE3ZjU4NzY2NGU0YTJiNDA5N2U5MmI1NzI4MmQzNmU2NGI1YjhiYWI5ODYzMTciLCJpYXQiOjE1ODUyMjc3MDEsIm5iZiI6MTU4NTIyNzcwMSwiZXhwIjoxNjE2NzYzNzAxLCJzdWIiOiIyMTI3Iiwic2NvcGVzIjpbXX0.of9f2LtFBjsHK8fx1j9tj2OEvdFESrEiJBYO4ttcV24T9B4t0eoNFf9WIGuvJmKTbuasoJB1m0ELKw6CpW9dby1wlj44OIXfTdf1rgCFXKyX4G453w1pAZUsHPm-QZdSpftDEek37OCb7JeOzH8AKl1vxqw1-QZBkm22IITmwBVcgOOClpx9_GoTu34ECw_xg7SAPALvnydagn52OMoRP-PZGKu86M9k2ghEjiydhZsBob8HTr2dDoyvMp1g2OzjNW2QLHUc0S4hfZ051UkBkg8eX376De90wIcP1ZNrcGotHarXdZ6af0dR8ma4t1r00EDLxrBuTZdvXQH--MmuAAN5Kel1GBj1YcVyQuBR75Vqs1Q1NY6UjEnPTCvK_dbzFHvfqK_-7e-oR6LU8uNpxEjL29kMp9umV4UuPyc0Acdq-3net_hy2AhC_4-qFdW3bUMqomoJY1S7CeRVPFuq0HxF4NWgGVQiRMPDa1Tw_S2v6IEye9OSG1wlhENhiaImW413PUAM6cG9rHHFLHIj1oduNKVtmUDB6_M9FXYskkMbMiojP_8MzbtHDDMouDu0m0xhjoiv2z-9Zy1h11sCueM0telrn2b5dlXczM8Mycj6OneHXuzQvDcGfzJ7bwygl_76h1D4nmmcXLoex0HKVqx52iQ3NqMDgx3DyTwZeZw"
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false


