- name: Discover Netgateway Server
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.netgateway.configs.get
    -  role: plusclouds.environment.information
  vars:
    - netgateway: "jGMNKKzNbK"
    - user_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjVlZmVmNzVkZGRkZjQxNmEyOWMyOGNkZDA5ZDRlNjc5NzFkMmIyMGVhMzZiNDczOGUzZDJkNTlhNTE3OTc3ZDk5NjFhODVjYTUzZTBhNDc1In0.eyJhdWQiOiIyNCIsImp0aSI6IjVlZmVmNzVkZGRkZjQxNmEyOWMyOGNkZDA5ZDRlNjc5NzFkMmIyMGVhMzZiNDczOGUzZDJkNTlhNTE3OTc3ZDk5NjFhODVjYTUzZTBhNDc1IiwiaWF0IjoxNjQ2NDg1NjA1LCJuYmYiOjE2NDY0ODU2MDUsImV4cCI6MTY3ODAyMTYwNSwic3ViIjoiMTMxMDAiLCJzY29wZXMiOltdfQ.GVvMUF58sYCAucZHhTutaYUtxqLyQnfoMwQCc38ctdiRjlqGCjLRv_gcxnaJu3GDQErZQblBvTkb5-6RnajHjbj7EW7e8BwYSC7y6UJz5fW7zR2UyWCsN_CIcKCbJrm1pmltDZ5R3h4jtVTSNztm7Bd8ErtYuVOEkz0VmxdYBl1GmoK6k9tH_C21g9Bs82i7gnYzBqQ56ubOrSb6b0xva5KZaK6kSlUgUyAqo1H9s2Rn5LF6Vp5zCI4HNkFKZpZLtwQ_CLht6QxiPz_qIpKU8royswlY96Wl3sZHQZJ7OxcMv-lxs21CTU6mfO7sXDn1POuojf2mrz8sUP_Mik0LfvsvOTxypZik5MTX-K8cFSPN_YyFNHoD-OgOmucVlN_vVXggARvEI_kj4_IdM_1B7oHm4U25duTf7lKoU1OPad1o42lueazmXtJ7Utg1qNUxw-rR0xUqdSSN8MEkvk-zYWVMTWwhBiymSgl8h8TmZ2QppAoUahhdyoLY8wvqkZsQdKRluwqNEWz6tExBHDjPr5DKiQTCgGqzT6pUM9w5wgq3lYvahIqBEBQW4FR8Vm41znLPQC_fgrJm5vzJjLS52v6nJynhaqc5Wtasx19IaK9FesrxzKFlaEcqCOAI_HmCZtrtXCxrhjmzGHOknA_dtDkSkt4BiYzICttXeh9G95Q

    - leo_url: http://10.100.0.114
- name: Install openvpn to Netgateway
  hosts: netgateway
  gather_facts: true
  roles:
    -  role: plusclouds.packetbender.openvpn/plusclouds.packetbender.openvpn.setup
  vars:
    - netgateway: "jGMNKKzNbK"
    - user_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjVlZmVmNzVkZGRkZjQxNmEyOWMyOGNkZDA5ZDRlNjc5NzFkMmIyMGVhMzZiNDczOGUzZDJkNTlhNTE3OTc3ZDk5NjFhODVjYTUzZTBhNDc1In0.eyJhdWQiOiIyNCIsImp0aSI6IjVlZmVmNzVkZGRkZjQxNmEyOWMyOGNkZDA5ZDRlNjc5NzFkMmIyMGVhMzZiNDczOGUzZDJkNTlhNTE3OTc3ZDk5NjFhODVjYTUzZTBhNDc1IiwiaWF0IjoxNjQ2NDg1NjA1LCJuYmYiOjE2NDY0ODU2MDUsImV4cCI6MTY3ODAyMTYwNSwic3ViIjoiMTMxMDAiLCJzY29wZXMiOltdfQ.GVvMUF58sYCAucZHhTutaYUtxqLyQnfoMwQCc38ctdiRjlqGCjLRv_gcxnaJu3GDQErZQblBvTkb5-6RnajHjbj7EW7e8BwYSC7y6UJz5fW7zR2UyWCsN_CIcKCbJrm1pmltDZ5R3h4jtVTSNztm7Bd8ErtYuVOEkz0VmxdYBl1GmoK6k9tH_C21g9Bs82i7gnYzBqQ56ubOrSb6b0xva5KZaK6kSlUgUyAqo1H9s2Rn5LF6Vp5zCI4HNkFKZpZLtwQ_CLht6QxiPz_qIpKU8royswlY96Wl3sZHQZJ7OxcMv-lxs21CTU6mfO7sXDn1POuojf2mrz8sUP_Mik0LfvsvOTxypZik5MTX-K8cFSPN_YyFNHoD-OgOmucVlN_vVXggARvEI_kj4_IdM_1B7oHm4U25duTf7lKoU1OPad1o42lueazmXtJ7Utg1qNUxw-rR0xUqdSSN8MEkvk-zYWVMTWwhBiymSgl8h8TmZ2QppAoUahhdyoLY8wvqkZsQdKRluwqNEWz6tExBHDjPr5DKiQTCgGqzT6pUM9w5wgq3lYvahIqBEBQW4FR8Vm41znLPQC_fgrJm5vzJjLS52v6nJynhaqc5Wtasx19IaK9FesrxzKFlaEcqCOAI_HmCZtrtXCxrhjmzGHOknA_dtDkSkt4BiYzICttXeh9G95Q

  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
