- name: Discover Netgateway Server
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.netgateway.configs.get
    -  role: plusclouds.environment.information
  vars:
    - netgateway: "oJXNMwVLEe"
    - user_token: ""
    - leo_url: http://10.100.0.114

- name: Install proxy to Netgateway
  hosts: netgateway
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.environment.information
    -  role: plusclouds.netgateway.configs.get
    -  role: plusclouds.netgateway.proxy.setup
  vars:
    - netgateway: "oJXNMwVLEe"
    - user_token: ""
    - leo_url: http://10.100.0.114
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false

