---
- name: Install netgateway services to server
  hosts: localhost
  become: false
  gather_facts: true
  ############### TRUE/FALSE API-LOCAL CONTROL
  roles:
   -  role: plusclouds.check.metadata
   -  role: plusclouds.environment.information
   -  role: plusclouds.netgateway.prepare
      when: not is_prepare_ready | bool
   -  role: plusclouds.netgateway.node.nginx.install
      when:
        - not is_proxy_installed | bool
        - is_loadbalancer_enabled == "1"
   -  role: plusclouds.netgateway.dhcp.setup
      when:
        - not is_dhcp_installed | bool
        - is_dhcp_enabled == "1"
   -  role: plusclouds.netgateway.dhcp.add.subnet
      when:
        - not is_dhcp_installed | bool
        - is_dhcp_enabled == "1"
   -  role: plusclouds.packetbender.openvpn/plusclouds.packetbender.openvpn.setup
      when:
        - not is_vpn_installed | bool
        - is_vpn_enabled == "1"
   -  role: plusclouds.netgateway.rsyslog.install
      when:
        - not is_rsyslog_installed | bool
        - is_rsyslog_enabled == "1"
   -  role: plusclouds.netgateway.pdns.install
      when:
        - not is_dns_installed | bool
        - is_dns_enabled == "1"

   ############## HASH CONTROL
   -  role: plusclouds.netgateway.iptables.update
      when: (iptables_hash != iptables_hash_meta)
   -  role: plusclouds.netgateway.loadbalancer.add
      when: (loadbalancer_hash != loadbalancer_hash_meta)
   -  role: plusclouds.packetbender.openvpn/plusclouds.packetbender.openvpn.add.client # eklemeler olacak
      when: (ovpnsrv_hash != ovpnsrv_hash_meta)
   -  role: plusclouds.netgateway.rsyslog.install
      when: (rsyslog_hash != rsyslog_hash_meta)
   -  role: plusclouds.netgateway.ntp.install
      when: (ntp_hash != ntp_hash_meta)
   -  role: plusclouds.netgateway.dhcp.add.subnet
      when: (subnet_hash != subnet_hash_meta)
      
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
  vars:
    - leo_url: "http://10.100.0.14"
    - user_token: ""
    - netgateway: "yDQLBJjLwm"