---
- name: Install netgateway services to server
  hosts: localhost
  become: false
  gather_facts: true
  roles:
   -  role: plusclouds.check.metadata
   -  role: plusclouds.netgateway.set.ipaddr
      when: not ipconf | bool
   -  role: plusclouds.netgateway.iptables.setup
      when: not iptables | bool
   -  role: plusclouds.netgateway.dhcp.setup
      when: not dhcpsrv | bool
   -  role: plusclouds.netgateway.dhcp.add.subnet
      when: not dhcpsrv | bool
   -  role: plusclouds.packetbender.openvpn/plusclouds.packetbender.openvpn.setup
      when: not ovpnsrv | bool
   -  role: plusclouds.netgateway.proxy.setup
      when: not proxysrv | bool
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
  vars:
    - leo_url: "http://api.plusclouds.com"

# set ip addresess
# install iptables
# install openvpn
# install proxy&loadbalancer
# install ntp
# install rsyslog
# install dhcp
# add subnets
