- name: Discover Netgateway Server
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.netgateway.configs.get
    -  role: plusclouds.environment.information
    -  role: plusclouds.netgateway.dhcp.set
  vars:
    - netgateway: "nMkNOZzrqW"
    - user_token: ""
    - leo_url: http://10.100.0.114

- name: Install isc-dhcp-server
  hosts: netgateway
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.netgateway.configs.get
    -  role: plusclouds.netgateway.dhcp.setup
    -  role: plusclouds.netgateway.dhcp.add.subnet
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
  vars:
    - user_token: ""
    - leo_url: http://10.100.0.114

