- name: Discover Netgateway Server
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.netgateway.configs.get
    -  role: plusclouds.environment.information
  vars:
    - netgateway: "BgmNvblNxe"
    - user_token: ""
    - leo_url: http://10.100.0.114

- name: Install NTP to Netgateway
  hosts: netgateway
  become: false
  gather_facts: false
  roles:
    -  role: plusclouds.environment.information
    -  role: plusclouds.netgateway.configs.get
    -  role: plusclouds.netgateway.ntp.install
  vars:
    - user_token: ""
    - leo_url: http://10.100.0.114
    - pools: "0.pool.ntp.org,1.pool.ntp.org,2.pool.ntp.org"
    - timezone: "Europe/Istanbul"
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false