---
- name: Set Static IP Addresses
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces

- name: install net-tools
  shell: apt update && apt install net-tools -y

- name: 
  shell: systemctl restart networking

- name: set mtu 9000
  shell: "{{ item }}"
  with_items:
    - ifconfig eth0 mtu 9000 up
    - ifconfig eth1 mtu 9000 up

- name: set hostname
  shell: hostnamectl set-hostname netgateway

- name: add myself to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost netgateway'
    state: present

- set_fact:
   ip_hash: "{{ netgateway_meta.json.data.networkHash }}"

- debug:
   var: ip_hash

- lineinfile:
    path: "{{ playbook_dir }}/hash.ini"
    regexp: '^ip_hash='
    line: ip_hash={{ ip_hash }}

- lineinfile:
    path: "{{ playbook_dir }}/installation.ini"
    regexp: '^ipconf='
    line: ipconf=true