---
# Cache de var mı yok mu diye kontrol et
- name: Check for netgateway cache
  local_action: stat path=cache/netgateway.cache
  register: cache_netgateway

# Eğer yok ise API'dan listeyi talep et
- name: Find netgateways server in related datacenter node
  uri:
    url: http://apiv2/v2/iaas/virtual-machines?tags=netgateway-{{ application }}&type=system&fields=ip_addr,networkcards,username,password
    method: GET
    headers:  
      Authorization: "Bearer {{ user_token }}"
    return_content: yes
    status_code: 200
    timeout: 300
  register: netgateway
  when: cache_netgateway.stat.exists == false
  delegate_to: localhost

# Eğer cache'de yok ise API'dan dönen sonucu cache'le
- name: Cache netgateway to file
  local_action: copy content="{{ netgateway }}" dest="cache/netgateway.cache"
  when: cache_netgateway.stat.exists == false
  delegate_to: localhost

# hypervisors'u cache'den geri getir
- name: Get netgateway from cache
  set_fact:
    netgateway: "{{ lookup('file', 'cache/netgateway.cache') }}"
  when: cache_netgateway.stat.exists == true
  delegate_to: localhost

- debug:
    var: netgateway.json.data