---
- set_fact:
    network: "{{ network }}"
  when: network is defined

- set_fact:
    wan: "{{ wan }}"
  when: wan is defined

- set_fact:
    netgateway: "{{ netgateway }}"
  when: netgateway is defined

- set_fact:
    netgateway: "{{ hostvars['localhost']['netgateway'] }}"
  when: hostvars['localhost']['netgateway'] is defined

- set_fact:
    datacenter_node: "{{ datacenter_node }}"
  when: datacenter_node is defined

- set_fact:
    vm_id: "{{ vm_id }}"
  when: vm_id is defined

- set_fact:
    vm_id: "{{ hostvars['localhost']['vm_id'] }}"
  when: hostvars['localhost']['vm_id'] is defined

- set_fact:
    network: "{{ hostvars['localhost']['network'] }}"
  when: hostvars['localhost']['network'] is defined

- set_fact:
    wan: "{{ hostvars['localhost']['wan'] }}"
  when: hostvars['localhost']['wan'] is defined

- set_fact:
    datacenter_node: "{{ hostvars['localhost']['datacenter_node'] }}"
  when: hostvars['localhost']['datacenter_node'] is defined
  
# API'dan listeyi talep et
- name: Find netgateways server in related datacenter node
  uri:
    url: http://apiv2/v2/iaas/virtual-machines/{{ vm_id }}?type=system&fields=ip_addr,username,password&include=datacenterNode
    method: GET
    headers:
      Authorization: "Bearer {{ user_token }}"
    return_content: yes
    status_code: 200
    timeout: 300
  register: netgateway_vm
  delegate_to: localhost

- debug:
    var: netgateway
- name: Add host to group netservers
  add_host:
    name: "{{ netgateway_vm.json.data.virtualNetworkCards.data.0.ipList.data.0.ip_addr }}"
    groups: netgateway
    ansible_ssh_user: "{{ netgateway_vm.json.data.username }}"
    ansible_ssh_pass: "{{ netgateway_vm.json.data.password }}"

- set_fact: 
    vlan_ip_addr: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.gateway }}"
    vlan_netmask: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.netmask }}"
    vlan_subnet: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.subnet }}"
    vlan_ip: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.ip_addr }}"
    vlan_broadcast: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.network }}"
    vlan_gateway: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.gateway }}"
    vlan_start_ip_range: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.ip_range_start }}"
    vlan_end_ip_range: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.ip_range_end }}"
    vlan_network: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.ip_addr }}{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.subnet }}"
    node_name: "{{ netgateway_vm.json.data.virtualNetworkCards.data.0.ipList.data.0.ip_addr }}"
    public_ip_addr: "{{ netgateway_vm.json.data.virtualNetworkCards.data.0.ipList.data.0.ip_addr }}"
    public_netmask: "{{ netgateway_vm.json.data.virtualNetworkCards.data.0.network.data.netmask }}"
    public_gateway: "{{ netgateway_vm.json.data.virtualNetworkCards.data.0.network.data.gateway }}"
    username: "{{ netgateway_vm.json.data.username }}"
    server_name: "{{ server_name }}"
    vm_id: "{{ vm_id }}"
    netgateway: "{{ netgateway }}"

#- shell: ssh-keygen -f "/root/.ssh/known_hosts" -R "{{ netgateway_vm.json.data.virtualNetworkCards.data.0.ipList.data.0.ip_addr }}"
#  ignore_errors: yes
