---
- set_fact:
    network: "{{ network }}"
  when: network is defined

- set_fact:
    wan: "{{ wan }}"
  when: wan is defined

- set_fact:
    network: "{{ hostvars['localhost']['network'] }}"
  when: hostvars['localhost']['network'] is defined

- set_fact:
    wan: "{{ hostvars['localhost']['wan'] }}"
  when: hostvars['localhost']['wan'] is defined


# API'dan listeyi talep et
- name: Find netgateways server in related datacenter node
  uri:
    url: http://apiv2/v2/iaas/virtual-machines?name={{ server_name }}&type=system&fields=ip_addr,username,password&include=datacenterNode
    method: GET
    headers:
      Authorization: "Bearer {{ user_token }}"
    return_content: yes
    status_code: 200
    timeout: 300
  register: netgateway
  delegate_to: localhost


- name: Add host to group netservers
  add_host:
    name: "{{ netgateway.json.data.0.virtualNetworkCards.data.0.ipList.data.0.ip_addr }}"
    groups: netgateway
    ansible_ssh_user: "{{ netgateway.json.data.0.username }}"
    ansible_ssh_pass: "{{ netgateway.json.data.0.password }}"

- set_fact: 
    vlan_ip_addr: "{{ netgateway.json.data.0.virtualNetworkCards.data.1.network.data.gateway }}"
    vlan_netmask: "{{ netgateway.json.data.0.virtualNetworkCards.data.1.network.data.netmask }}"
    vlan_subnet: "{{ netgateway.json.data.0.virtualNetworkCards.data.1.network.data.subnet }}"
    vlan_ip: "{{ netgateway.json.data.0.virtualNetworkCards.data.1.network.data.ip_addr }}"
    vlan_broadcast: "{{ netgateway.json.data.0.virtualNetworkCards.data.1.network.data.network }}"
    vlan_gateway: "{{ netgateway.json.data.0.virtualNetworkCards.data.1.network.data.gateway }}"
    vlan_start_ip_range: "{{ netgateway.json.data.0.virtualNetworkCards.data.1.network.data.ip_range_start }}"
    vlan_end_ip_range: "{{ netgateway.json.data.0.virtualNetworkCards.data.1.network.data.ip_range_end }}"
    vlan_network: "{{ netgateway.json.data.0.virtualNetworkCards.data.1.network.data.ip_addr }}{{ netgateway.json.data.0.virtualNetworkCards.data.1.network.data.subnet }}"
    node_name: "{{ netgateway.json.data.0.virtualNetworkCards.data.0.ipList.data.0.ip_addr }}"
    public_ip_addr: "{{ netgateway.json.data.0.virtualNetworkCards.data.0.ipList.data.0.ip_addr }}"
    public_netmask: "{{ netgateway.json.data.0.virtualNetworkCards.data.0.network.data.netmask }}"
    public_gateway: "{{ netgateway.json.data.0.virtualNetworkCards.data.0.network.data.gateway }}"
    datacenterNode: "{{ netgateway.json.data.0.datacenterNode.data.id }}"
    vm_id: "{{ netgateway.json.data.0.id }}"
    username: "root"

