---
- set_fact:
    network: "{{ network }}"
  when: network is defined

- set_fact:
    wan: "{{ wan }}"
  when: wan is defined

- set_fact:
    netgateway: "{{ netgateway }}"
  when: netgateway is defined

- set_fact:
    netgateway: "{{ hostvars['localhost']['netgateway'] }}"
  when: hostvars['localhost']['netgateway'] is defined

- set_fact:
    datacenter_node: "{{ datacenter_node }}"
  when: datacenter_node is defined

- set_fact:
    vm_id: "{{ netgateway_meta.json.data.virtual_machine_id }}"

- set_fact:
    vm_id: "{{ hostvars['localhost']['vm_id'] }}"
  when: hostvars['localhost']['vm_id'] is defined

- set_fact:
    network: "{{ hostvars['localhost']['network'] }}"
  when: hostvars['localhost']['network'] is defined

- set_fact:
    wan: "{{ hostvars['localhost']['wan'] }}"
  when: hostvars['localhost']['wan'] is defined

- set_fact:
    datacenter_node: "{{ hostvars['localhost']['datacenter_node'] }}"
  when: hostvars['localhost']['datacenter_node'] is defined

# API'dan listeyi talep et
- name: Find netgateways server in related datacenter node
  uri:
    url: "{{leo_url}}/v2/packetbender/netgateways/metadata?uuid=b984eec5-67a3-b1d6-2fca-993437b7f8ef"
    method: GET
    headers:
      Authorization: "Bearer {{ user_token }}"
    return_content: yes
    status_code: 200
    timeout: 300
  register: netgateway_vm
  delegate_to: localhost

- debug:
    var: netgateway_vm

- name: Add host to group netgateways
  add_host:
    name: "{{ netgateway_vm.json.data.virtualNetworkCards.data.0.ipList.data.0.ip_addr }}"
    groups: netgateway
    ansible_ssh_user: "{{ netgateway_vm.json.data.username }}"
    ansible_ssh_pass: "{{ netgateway_vm.json.data.password }}"
    vlan_ip_addr: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.gateway }}"
    vlan_netmask: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.netmask }}"
    vlan_subnet: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.subnet }}"
    vlan_ip: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.ip_addr }}"
    vlan_broadcast: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.network }}"
    vlan_gateway: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.gateway }}"
    vlan_start_ip_range: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.ip_range_start }}"
    vlan_end_ip_range: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.ip_range_end }}"
    vlan_network: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.ip_addr }}{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.subnet }}"
    node_name: "{{ netgateway_vm.json.data.virtualNetworkCards.data.0.ipList.data.0.ip_addr }}"
    public_ip_addr: "{{ netgateway_vm.json.data.virtualNetworkCards.data.0.ipList.data.0.ip_addr }}"
    public_netmask: "{{ netgateway_vm.json.data.virtualNetworkCards.data.0.network.data.netmask }}"
    public_gateway: "{{ netgateway_vm.json.data.virtualNetworkCards.data.0.network.data.gateway }}"
    nginx_conf: "{{ netgateway_vm.json.data.loadBalancer.nginx_conf }}"
    #nginx_host_config: "{{ netgateway_vm.json.data.loadBalancer.0.hosts }}"
    fastcgi_conf: "{{ netgateway_vm.json.data.loadBalancer.fastcgi_conf }}"
    proxy_conf: "{{ netgateway_vm.json.data.loadBalancer.proxy_conf }}"
    mimes_conf: "{{ netgateway_vm.json.data.loadBalancer.mimes_conf }}"
    #public_ip_addr: 185.44.192.47
    #public_netmask: 255.255.255.0
    #public_gateway: 185.44.192.1
    #network: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.id }}"
    username: "{{ netgateway_vm.json.data.username }}"
    vm_id: "{{ vm_id }}"
    netgateway: "{{ netgateway }}"

- set_fact:
    vlan_ip_addr: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.gateway }}"
    vlan_netmask: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.netmask }}"
    vlan_subnet: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.subnet }}"
    vlan_ip: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.ip_addr }}"
    vlan_broadcast: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.network }}"
    vlan_gateway: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.gateway }}"
    vlan_start_ip_range: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.ip_range_start }}"
    vlan_end_ip_range: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.ip_range_end }}"
    vlan_network: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.ip_addr }}{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.subnet }}"
    node_name: "{{ netgateway_vm.json.data.virtualNetworkCards.data.0.ipList.data.0.ip_addr }}"
    public_ip_addr: "{{ netgateway_vm.json.data.virtualNetworkCards.data.0.ipList.data.0.ip_addr }}"
    public_netmask: "{{ netgateway_vm.json.data.virtualNetworkCards.data.0.network.data.netmask }}"
    public_gateway: "{{ netgateway_vm.json.data.virtualNetworkCards.data.0.network.data.gateway }}"
    nginx_conf: "{{ netgateway_vm.json.data.loadBalancer.nginx_conf }}"
    #nginx_host_config: "{{ netgateway_vm.json.data.loadBalancer.0.hosts }}"
    fastcgi_conf: "{{ netgateway_vm.json.data.loadBalancer.fastcgi_conf }}"
    proxy_conf: "{{ netgateway_vm.json.data.loadBalancer.proxy_conf }}"
    mimes_conf: "{{ netgateway_vm.json.data.loadBalancer.mimes_conf }}"
    #public_ip_addr: 185.44.192.47
    #public_netmask: 255.255.255.0
    #public_gateway: 185.44.192.1
    #network: "{{ netgateway_vm.json.data.virtualNetworkCards.data.1.network.data.id }}"
    username: "{{ netgateway_vm.json.data.username }}"
    vm_id: "{{ vm_id }}"
    netgateway: "{{ netgateway }}"

#- shell: ssh-keygen -f "/root/.ssh/known_hosts" -R "{{ netgateway_vm.json.data.virtualNetworkCards.data.0.ipList.data.0.ip_addr }}"
#  ignore_errors: yes
