- name: make sure ip_forwarding enabled
  shell: echo 1 > /proc/sys/net/ipv4/ip_forward
  
- name: backup iptables
  shell: iptables-save > /home/iptables.old

- name: Copy iptables-rules to home
  template:
    src: iptables-save.j2
    dest: /home/iptables.out

- name: Flush filter rules
  shell: iptables -F
  
- name: Flush nat rules
  shell: iptables -F -t nat 

- name: Apply rules
  shell: iptables-restore /home/iptables.out

- name: Install iptables-persistent
  apt:
    name: iptables-persistent
    state: "present"

- name: Forward rules to persistent save file
  template:
    src: iptables-save.j2
    dest: /etc/iptables/rules.v4

- name: Save iptables rules
  shell: "iptables-save > /etc/iptables/rules.v4"

- set_fact:
   iptables_hash: "{{ netgateway_meta.json.data.firewallHash }}"

- debug:
   var: iptables_hash