---
- name: restart openresty
  service:
    name: openresty
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: Enable init.d
  service:
    name: nginx
    state: started
    enabled: yes

#- name: Enable init.d
#  shell: nginx -s reopen