---
- name: Set username to netgateway server
  uri:
    url: "{{leo_url}}/v2/iaas/virtual-machines/{{ vm_id }}/save-username"
    method: PUT
    headers:
      Authorization: "Bearer {{ user_token }}"
    body: "username={{ username }}"
    return_content: yes
    status_code: 204
    timeout: 200
  delegate_to: localhost

- name: Set password to netgateway server
  uri:
    url: "{{leo_url}}/v2/iaas/virtual-machines/{{ vm_id }}/save-password"
    method: PUT
    headers:
      Authorization: "Bearer {{ user_token }}"
    body: "password={{ password.json.data.password }}&password_confirmation={{ password.json.data.password }}"
    return_content: yes
    status_code: 204
    timeout: 200
  delegate_to: localhost
