---
- set_fact:
    pool_list: []

- name: Create the list
  set_fact: 
    pool_list: "{{ pools.split(',') }}"

- name: Install ntp-server
  apt:
   name: "{{ item }}"
   state: latest
  with_items:
   - ntp
   - ntpstat
   - ntpdate

- name: configuring ntp.conf
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf

- name: Add pools to ntp conf file
  lineinfile:
    path: /etc/ntp.conf
    line: pool {{ item }} iburst
  with_items: 
    - "{{ pool_list }}"
    
- name: Set Timezone
  shell: timedatectl set-timezone {{ timezone }}

- name: reload ntp server
  service: name=ntp state=restarted