---
#- set_fact:
#    pool_list: []

- set_fact:
    timezone: "{{ netgateway_meta.json.data.ntp.timezone }}"

- set_fact:
    pools: "{{ netgateway_meta.json.data.ntp.pools }}"

- debug:
    var: pools

- debug:
    var: timezone

#- name: Create the list
#  set_fact: 
#    pool_list: "{{ pools.split(',') }}"

- name: Install ntp-server
  apt:
   name: "{{ item }}"
   state: latest
  with_items:
   - ntp
   - ntpstat
   - ntpdate

- name: configuring ntp.conf
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf

- name: Add pools to ntp conf file
  lineinfile:
    path: /etc/ntp.conf
    line: pool {{ item }} iburst
  loop: "{{ pools }}"
    
- name: Set Timezone
  shell: timedatectl set-timezone {{ timezone }}

- name: reload ntp server
  service: name=ntp state=restarted