---
- name: Boot the server
  uri:
    url: "{{leo_url}}/v2/iaas/virtual-machines/{{ cloned_vm.json.data.id }}/start"
    method: PUT
    headers:
      Authorization: "Bearer {{ user_token }}"
    return_content: yes
    status_code: 204
    timeout: 300

- name: Wait for ping loss
  local_action: shell ping -q -c 1 -W 1 {{ public_ip_address.json.data.ip_addr }}
  register: res
  retries: 50
  until: ('100% packet loss' not in res.stdout)
