- name: include variables
  include_vars: "{{ playbook_dir }}/config.yml"

- name: find all vms with name {{ application }}
  uri:
    url: http://apiv2/v2/iaas/virtual-machines?name=netgateway-{{ application }}&datacenterNode={{ preferred_node }}
    method: GET
    headers:
      Authorization: "Bearer {{ user_token }}"
    return_content: yes
    status_code: 200
    timeout: 300
  delegate_to: localhost
  register: cloned_vm

- name: "Force shutdown !!!!!!!!!!"
  uri:
    url: http://apiv2/v2/iaas/virtual-machines/{{ item.id }}/shutdown
    method: PUT
    headers:
      Authorization: "Bearer {{ user_token }}"
    body: "force=1"
    return_content: yes
    status_code: 204
  with_items: "{{ cloned_vm.json.data }}"

- name: "Delete halted VM !!!!!!!!!!"
  uri:
    url: http://apiv2/v2/iaas/virtual-machines/{{ item.id }}
    method: DELETE
    headers:
      Authorization: "Bearer {{ user_token }}"
    body: "force=1"
    return_content: yes
    status_code: 204
  ignore_errors: True
  with_items: "{{ cloned_vm.json.data }}"

- meta: end_play