---
- name: Clone the template
  uri:
    url: http://apiv2/v2/iaas/virtual-machines/{{ template }}/clone
    body: "name={{ server_name }}&total_cpu={{ cpu }}&total_ram={{ ram_size }}&total_disk={{ disk_size }}"
    method: POST
    headers:
      Authorization: "Bearer {{ user_token }}"
    return_content: yes
    status_code: 201
    timeout: 300
  register: cloned_vm

- debug: 
    var: cloned_vm

- name: Wait until the template is cloned
  uri:
    url: http://apiv2/v2/iaas/virtual-machines/{{ cloned_vm.json.data.id }}/status
    method: GET
    headers:
      Authorization: "Bearer {{ user_token }}"
    return_content: yes
    status_code: 200
    timeout: 300
  register: cloned_vm_status
  until: cloned_vm_status.json.data.status == "halted"
  retries: 10
  delay: 3