- set_fact:
    public_network_card_ref: "{{ wan }}"

- name: Set Virtual Interface 0 for cloned vm
  uri:
    url: http://apiv2/v2/iaas/virtual-machines/{{ cloned_vm.json.data.id }}/set-network-card
    method: PUT
    headers:
      Authorization: "Bearer {{ user_token }}"
    body: "name={{ server_name }}_vif_0&network_ref={{ public_network_card_ref }}&device=0"
    return_content: yes
    status_code: 201
  register: cloned_vm_vif0

- name: wait for config apply
  wait_for:
    timeout: 10

- debug:
    var: cloned_vm_vif0.json.data

- name: Set Virtual Interface 1 for cloned vm
  uri:
    url: http://apiv2/v2/iaas/virtual-machines/{{ cloned_vm.json.data.id }}/set-network-card
    method: PUT
    headers:
      Authorization: "Bearer {{ user_token }}"
    body: "name={{ server_name }}_vif_1&network_ref={{ network }}&device=1"
    return_content: yes
    status_code: 201
  register: cloned_vm_vif1

- name: wait for config apply
  wait_for:
    timeout: 10

- debug:
    var: cloned_vm_vif1.json.data

- name: Add new IP to VIF0
  uri:
    url: http://apiv2/v2/packetbender/ip
    method: POST
    headers:
      Authorization: "Bearer {{ user_token }}"
    body: "network_ref={{ public_network_card_ref }}&virtual_network_card_ref={{ cloned_vm_vif0.json.data.id }}&allow=1"
    status_code: 201
  register: public_ip_address

- name: wait for config apply
  wait_for:
    timeout: 20
