- name: Find netgateways firewall conf
  uri:
    url: {{leo_url}}/v2/packetbender/netgateways/{{ netgateway }}/firewall
    method: GET
    headers:
      Authorization: "Bearer {{ user_token }}"
    return_content: yes
    status_code: 200
    timeout: 300
  register: firewall_conf
  delegate_to: localhost
