- name: Find netgateways proxy conf
  uri:
    url: http://apiv2/v2/packetbender/netgateways/{{ netgateway }}/proxy
    method: GET
    headers:
      Authorization: "Bearer {{ user_token }}"
    return_content: yes
    status_code: 200
    timeout: 300
  register: proxy_conf
  delegate_to: localhost
