- name: Find netgateways nat conf
  uri:
    url: {{leo_url}}/v2/packetbender/netgateways/{{ netgateway }}/nat
    method: GET
    headers:
      Authorization: "Bearer {{ user_token }}"
    return_content: yes
    status_code: 200
    timeout: 300
  register: nat_conf
  delegate_to: localhost
