- name: Find netgateways ntp conf
  uri:
    url: http://apiv2/v2/packetbender/netgateways/{{ netgateway_id }}/ntp
    method: GET
    headers:
      Authorization: "Bearer {{ user_token }}"
    return_content: yes
    status_code: 200
    timeout: 300
  register: ntp_conf
  delegate_to: localhost

- set_fact:
    pools: "{{ntp_conf.json.pools}}"
    timezone: "{{ntp_conf.json.timezone}}"

- debug: 
    var: timezone
- debug: 
    var: pools
    