- name: Creates directory
  file: path=/etc/dhcp/subnets state=directory

- name: Copy the Customize subnet file
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/subnets/{{ netgateway_meta.json.data.virtualNetworkCards.data.1.network.data.ip_range_start }}-{{ netgateway_meta.json.data.virtualNetworkCards.data.1.network.data.ip_range_end }}.conf

- name: Set dhcp config file
  lineinfile:
    path: /etc/dhcp/dhcpd.conf
    line: 'include "/etc/dhcp/subnets/{{ netgateway_meta.json.data.virtualNetworkCards.data.1.network.data.ip_range_start }}-{{ netgateway_meta.json.data.virtualNetworkCards.data.1.network.data.ip_range_end }}.conf";'
    backup: "{{ backup }}"

- name: Copy the Customize subnet file
  template:
    src: isc-dhcp-server.j2
    dest: /etc/default/isc-dhcp-server

- name: delete v6 confs
  file:
    path: /etc/dhcp/dhcpd6.conf
    state: absent

- name: Restart DHCP service
  command: "/etc/init.d/isc-dhcp-server restart"

- set_fact:
    subnet_hash: "{{ netgateway_meta.json.data.networkHash }}"

- debug:
    var: subnet_hash